In [2]:
import numpy as np

In [3]:
# NumPyの配列を作る
a = np.array([0, 1, 2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int64


In [4]:
b = np.array([1, 1.5, 2])
print(b)
print(b.dtype)

c = np.array([1 + 2j, 3 + 4j, 5 + 6j])
print(c)
print(c.dtype)

d = np.array([True, False, True, False, False])
print(d)
print(d.dtype)

e = np.array(list("TechAcademy"))
print(e)
print(e.dtype)

[1.  1.5 2. ]
float64
[1.+2.j 3.+4.j 5.+6.j]
complex128
[ True False  True False False]
bool
['T' 'e' 'c' 'h' 'A' 'c' 'a' 'd' 'e' 'm' 'y']
<U1


In [5]:
# 小さい数字を使いたい場合
# -> デフォルトがint64でメモリやHDDの容量を無駄にする可能性があるのでそんなに使わない場合には指定もできる
f = np.array([100, 200, 300], dtype = np.int16)
print(f)
print(f.dtype)

[100 200 300]
int16


In [8]:
# 既に存在するndarrayのデータ型を変換する
g = np.array([1.5, 2.5, 3.5])
print(g)
print(g.dtype)

g = g.astype(np.int64)  # データ型の変換
print(g)
print(g.dtype)

[1.5 2.5 3.5]
float64
[1 2 3]
int64


In [20]:
# 配列の作成に便利なメソッド

# arange() -> range()と引数の指定の仕方は一緒
a = np.arange(20)
print(a)

b = np.arange(1, 21)
print(b)

c = np.arange(2, 41, 2)
print(c)


# linspace(a, b, c) -> a以上b以下の数値をc分割したもの
d = np.linspace(0, 10, 5)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 0.   2.5  5.   7.5 10. ]


In [23]:
# empty() -> とりあえず先に指定の要素数をもつ配列だけ用意する
e = np.empty(5)
print(e)  # 各要素の初期化はしないので、そのときによって値はバラバラになる

# zeros() -> empty()と使い方は一緒で、全ての要素を0で初期化したものを作る
f = np.zeros(5)
print(f)

# ones() -> 1で初期化
f_ones = np.ones(5)
print(f_ones)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [34]:
# random.rand() -> 全ての要素をランダムな数値で初期化
g = np.random.rand(5)
print(g)  # 1より小さい小数になる

# 1から6までの整数値にしたい場合
g = g * 6 + 1
g = g.astype(np.int8)
print(g)

# tolist() -> 配列(ndarray)からリストに変換
gl = g.tolist()
gl.pop()
print(gl)

[0.09273815 0.96859256 0.48988974 0.12620386 0.44343206]
[1 6 3 1 3]
[1, 6, 3, 1]


In [33]:
# concatenate() -> 既にある２つの配列を連結させたい場合
h = np.arange(1, 4)
i = np.arange(4, 7)
j = np.concatenate([h, i])
print(j)

[1 2 3 4 5 6]


In [45]:
# 多次元配列の作成
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

# empty()を利用する場合 -> 引数（縦の要素数, 横の要素数） タプル形式
b = np.empty((2, 3), dtype=np.int64)
b[0] = [1, 2, 3]
b[1] = [4, 5, 6]
print(b)


# reshape() -> １次元配列を多次元配列に変換
c = np.arange(1, 21)
print(c)
print(c.shape)
d = c.reshape(4, 5)  # 引数(縦, 横) -> 元の要素すうと同数になる必要がある
print(d)
print(d.shape)
d2 = c.reshape(2, 2, 5)
print(d2)


# flatten(), ravel() -> 多次元配列を１次元配列に変換(ravelは元の配列が無くなる代わりに処理が高速)
e = np.arange(1, 21).reshape(4, 5)
f = e.flatten()
print(e)
print(f)

g = e.ravel()
print(e)
print(g)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# 要素の参照と更新
a = np.arange(1, 101).reshape(10, 10)
print(a[0, 0])
print(a[1, 1])
print(a[1:3, 1:3])
print(a[1:5:3, 1:5:3])
print(a[:5, :5])
print(a[7:, 7:])
print(a[::3, ::3])
print(a[:, :])

1
12
[[12 13]
 [22 23]]
[[12 15]
 [42 45]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
[[ 78  79  80]
 [ 88  89  90]
 [ 98  99 100]]
[[  1   4   7  10]
 [ 31  34  37  40]
 [ 61  64  67  70]
 [ 91  94  97 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [8]:
# 要素の新規追加
# append(配列, 追加要素) -> 配列の末尾に追加
a = np.arange(1, 20)
a = np.append(a, 20)
a = np.append(a, (21, 22, 23, 24))
print(a)

# insert(配列, 追加したい場所, 追加要素) -> 特定の場所に追加
b = np.arange(1, 6)
b = np.insert(b, 1, 6)
b = np.insert(b, 3, (7, 8))
print(b)


# 多次元配列へのinsert() -> ４つ目の引数（０の場合は横に１行、１の場合は縦に１列）
c = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
d = np.array([1, 1, 1])
(h, v) = c.shape  # 縦の要素数と横の要素数取得

e = np.insert(c, 2, d, 0)
print(e)
f = np.insert(c, h, d, 0)
print(f)
g = np.insert(c, 2, d, 1)
print(g)
h = np.insert(c, v, d, 1)
print(h)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[1 6 2 7 8 3 4 5]
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]
[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [10]:
# 要素の削除
a = np.arange(5)
a = np.delete(a, 2)
print(a)

# 多次元配列の場合、引数が増える -> ０の場合は１行丸ごと、１の場合は１列丸ごと削除
b = np.arange(1, 26).reshape(5, 5)
b = np.delete(b, 1, 0)  # 行の削除
print(b)

c = np.arange(1, 26).reshape(5, 5)
c = np.delete(c, 1, 1)  # 列の削除
print(c)

[0 1 3 4]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  3  4  5]
 [ 6  8  9 10]
 [11 13 14 15]
 [16 18 19 20]
 [21 23 24 25]]


In [14]:
# 配列の四則演算
a = np.arange(1, 11)
print(a)
print(a + 1)
print(a - 1)
print(a * 2)
print(a / 2)
print(a % 2)

# 配列同士の演算
b = np.arange(1, 7).reshape(2, 3)
c = np.arange(7, 13).reshape(2, 3)
print(c + b)
print(c - b)

d = np.arange(1, 5).reshape(2, 2)
e = np.arange(5, 9).reshape(2, 2)
print(d * e)
print(d / e)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18 20]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[1 0 1 0 1 0 1 0 1 0]
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
# ユニバーサル関数 -> 一度に全要素への計算処理を適用し、結果を新たな配列にする
# floor(), ceil(), round()など
a = np.random.rand(5)
print(a)

a = a * 6 + 1

print(a)
print(np.array(np.floor(a), dtype=np.int64))  # 小数点以下切り捨て
print(np.array(np.ceil(a), dtype=np.int64))  # 小数点以下切り上げ
print(np.array(np.round(a), dtype=np.int64))  #小数点以下四捨五入

[0.91555708 0.39535567 0.05779214 0.03049818 0.73565572]
[6.49334251 3.37213404 1.34675285 1.1829891  5.41393431]
[6 3 1 1 5]
[7 4 2 2 6]
[6 3 1 1 5]


In [24]:
# 行列の反転と回転
a = np.arange(1, 10).reshape(3, 3)
print(a)

# 左右反転 -> fliplr()
b = np.fliplr(a)
print(b)

# 上下反転 -> flipud()
c = np.flipud(a)
print(c)

# 反時計回りに９０度回転 -> rot90() 第２引数は回転数
d = np.rot90(a, 1)
print(d)
e = np.rot90(a, 2)
print(e)
f = np.rot90(a, 3)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [25]:
# 練習問題 -> 掛け算の九九の表を２次元配列として作成するプログラム(２通り)
# ①
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(1, 10)
b = b.reshape(9, 1)
c = a * b
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [27]:
# ②
import numpy as np

d = np.zeros((9, 9))
d = d.astype(np.int8)

for i in range(9):
    for j in range(9):
        d[i, j] = (i + 1) * (j + 1)
        
print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
